/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Clases.*;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Josua
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    Restaurante restauran = iiproyecto.main.restaurante;
    Clases.Menu menu; //ara que no lo confunda con la ventana
    ArrayList<Plato> plato;
    Plato nuevoPlato;
    String ingr = "";
    Orden orden;
    Restaurante enlace; //para acceder a datos del restaurante
    ArrayList<Bebida> bebida;

    public Menu(Orden orden) { //recibe la orden con la que hay que trabajar;
        initComponents();
        this.orden = orden;  //se referencia la orden deseada
        enlace = iiproyecto.main.restaurante;
        this.n.setVisible(false);
        this.n2.setVisible(false);
        this.nuevoC.setVisible(false);
        this.c.setVisible(false);
        this.nuevoI.setVisible(false);
        this.nuevoNom.setVisible(false);
        this.nuevoPrecio.setVisible(false);
        this.n3.setVisible(false);
        this.n4.setVisible(false);
        this.n5.setVisible(false);  //acceso a botones y labels en falso
        this.n6.setVisible(false);
        this.fuera.setVisible(true);
        this.addIngredient.setVisible(false);
        this.addToMenu.setVisible(false);
        this.setLocationRelativeTo(null);

        this.getContentPane().setBackground(new Color(160, 200, 240));
        menu = restauran.getMenu();
        plato = menu.getPlatos();
        texto.setEditable(false);
        mensaje.setText(orden.getMesero().getNombre() + " espera por su orden");

        // se escribe el menu
        for (int i = 0; i < plato.size(); i++) {
            Plato dish = plato.get(i);
            String tex = "";
            if (dish.getIngredientes() != null) {
                String[] ar = dish.getIngredientes();
                for (int x = 0; x < ar.length; x++) {

                    tex += ar[x];
                    tex += ",";
                }
                tex = tex.substring(0, tex.length() - 1); //modificando cadena
                texto.append(" " + dish.getNumero() + " " + dish.getNombre() + " " + " Ingredientes: " + tex + " " + dish.getPrecio() + " Colones" + " " + " Calorías: " + dish.getCalorias() + "\n"); //escribiendo datos de plato

            } else {
                texto.append(" " + dish.getNumero() + " " + dish.getNombre() + " Precio:" + " " + dish.getPrecio() + " Colones" + " " + " Calorías: " + dish.getCalorias() + "\n"); //escribiendo datos de plato
            }
        }

        bebida = menu.getBebidas();

        for (int i = 0; i < bebida.size(); i++) {
            Bebida beverage = bebida.get(i);

            texto.append(" " + beverage.getNumero() + " " + beverage.getNombre() + " " + beverage.getPrecio() + " Colones" + " " + beverage.getMiliLitros() + " ml" + "\n");

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        mensaje = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        numeroPlato = new javax.swing.JTextField();
        cant = new javax.swing.JLabel();
        cantid = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        eleccion = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        fuera = new javax.swing.JButton();
        n = new javax.swing.JLabel();
        addToMenu = new javax.swing.JButton();
        nuevoNom = new javax.swing.JTextField();
        n2 = new javax.swing.JLabel();
        nuevoPrecio = new javax.swing.JTextField();
        n3 = new javax.swing.JLabel();
        addIngredient = new javax.swing.JButton();
        nuevoI = new javax.swing.JTextField();
        n4 = new javax.swing.JLabel();
        nuevoC = new javax.swing.JTextField();
        n5 = new javax.swing.JLabel();
        n6 = new javax.swing.JLabel();
        c = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU RESTAURANTE Y SISTEMA DE ORDENADO");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Adobe Arabic", 0, 18)); // NOI18N
        setResizable(false);

        jLabel1.setBackground(new java.awt.Color(255, 102, 102));
        jLabel1.setFont(new java.awt.Font("PMingLiU", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Menú del restaurante");

        texto.setBackground(new java.awt.Color(236, 247, 192));
        texto.setColumns(20);
        texto.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        texto.setRows(5);
        jScrollPane1.setViewportView(texto);

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 153));
        jLabel2.setText("Número Plato");

        jLabel3.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 153));
        jLabel3.setText("Nombre Artículo");

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 153));
        jLabel4.setText("Precio");

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel5.setText("Estimado Cliente: ");

        mensaje.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel6.setText("Digite el número del articulo ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel7.setText("a agregar a su orden");

        cant.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        cant.setText("Cantidad a consumir");

        add.setText("Agregar ");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jButton1.setText("Finalizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel8.setText("El producto es");

        eleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plato", "Bebida" }));

        jLabel9.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 153));
        jLabel9.setText("Ingredientes");

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 153));
        jLabel10.setText("Otros Detalles");

        fuera.setText("Plato fuera de menu");
        fuera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fueraActionPerformed(evt);
            }
        });

        n.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        n.setText("Nombre del Plato");

        addToMenu.setText("Agregar a menu");
        addToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToMenuActionPerformed(evt);
            }
        });

        n2.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        n2.setText("Precio");

        n3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        n3.setText("Ingredientes");

        addIngredient.setText("Agregar Ingrediente");
        addIngredient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIngredientActionPerformed(evt);
            }
        });

        n4.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        n4.setText("Calorias");

        n5.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        n5.setText("Cantidad a Consumir");

        n6.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        n6.setText("Del Plato Nuevo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 56, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fuera, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(n, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(n2, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(nuevoNom, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(nuevoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(n3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nuevoI, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(n4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nuevoC, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(n6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(addToMenu))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(n5, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(116, 116, 116)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numeroPlato, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cant, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel8)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButton1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cantid, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(125, 125, 125)
                                        .addComponent(eleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(add)))
                                .addGap(19, 19, 19))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(160, 160, 160))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(addIngredient, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(108, 108, 108))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cant)
                    .addComponent(jLabel8))
                .addGap(9, 9, 9)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroPlato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cantid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fuera)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n)
                    .addComponent(n2)
                    .addComponent(n3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nuevoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addIngredient)
                    .addComponent(nuevoI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(n4)
                    .addComponent(n5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nuevoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addToMenu)
                    .addComponent(n6)
                    .addComponent(c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:

        if ((!numeroPlato.getText().equals("")) && (!cant.getText().equals(""))) {

            try {
                int numero = Integer.parseInt(numeroPlato.getText());
                int cantidad = Integer.parseInt(cantid.getText());

                if (eleccion.getSelectedIndex() == 0) { //si se eligió un plato
                    Plato plato = enlace.getMenu().buscarPlatillo(numero);

                    if (plato != null) { //si el plato existe
                        plato.setVecesConsumido(plato.getVecesConsumido() + ((plato.getVecesConsumido()) * cantidad));
                        Plato pl = plato.clone();
                        System.out.println(pl.getPrecio());
                        orden.agregarPlato(pl, cantidad); //un cllon del plato se va a la orden
                        for (int i = 0; i < cantidad; i++) {
                            pl = plato.clone();
                            Pedido pedido = new Pedido(false); //espera a ser preparado
                            pedido.setPlato(pl); //se añaded el clon
                            enlace.añadirCola(pedido); //se agrega a la lista global de los pediods del restaurante
                        }
                        JOptionPane.showMessageDialog(this, " Producto agregado con éxito", "Notificación", 1);

                    } else {
                        JOptionPane.showMessageDialog(this, " El numero ingresado no pertenece a ningún plato del menu", "Alerta de sistema", 0);
                    }

                } else { //si fue una bebida
                    Bebida beverage = enlace.getMenu().buscarBebida(numero);

                    if (beverage != null) { //si la bebida existe
                        beverage.setVecesConsumido(beverage.getVecesConsumido() + ((beverage.getVecesConsumido()) * cantidad));
                        Bebida beb = beverage.clone();
                        System.out.println(beb.getPrecio());
                        orden.agregarBebida(beb, cantidad); //un clon de la bebida se va a la orden
                        for (int i = 0; i < cantidad; i++) { //se añade las veces que se pidio
                            Pedido pedido = new Pedido(false); //espera a ser preparado
                            pedido.setBebida(beb); //se añaded el clon
                            enlace.añadirCola(pedido); //se agrega a la lista global de los pediods del restaurante
                        }
                        JOptionPane.showMessageDialog(this, " Producto agregado con éxito", "Notificación", 1);

                    } else {
                        JOptionPane.showMessageDialog(this, " El numero ingresado no pertenece a ningúna bebida del menu", "Alerta de sistema", 0);
                    }

                }

            } catch (NumberFormatException e) {

                JOptionPane.showMessageDialog(this, " Alguno de los datos no representa un número", "Alerta de sistema", 0);
            } finally {

                numeroPlato.setText("");
                cantid.setText("");
            }

        } else {
            JOptionPane.showMessageDialog(this, " Los datos ingresados son incorrectos  ", " Alerta de sistema ", 0);
        }

    }//GEN-LAST:event_addActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, orden.getMesero().getNombre() + " ha tomado su orden con éxito", " Notificación ", 1);
        this.dispose();
        iiproyecto.main.ventana.setVisible(true); //visualizar ventana

    }//GEN-LAST:event_jButton1ActionPerformed

    private void addToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToMenuActionPerformed
        // TODO add your handling code here:
        if ((!this.nuevoNom.getText().equals("")) && (!this.nuevoPrecio.getText().equals("")) && (!this.nuevoC.getText().equals("")) && (!this.c.getText().equals(""))) {
            try {
                int p = Integer.parseInt(this.nuevoPrecio.getText());
                int cc = Integer.parseInt(this.nuevoC.getText());
                int can = Integer.parseInt(this.c.getText());
                this.ingr = this.ingr.substring(0, this.ingr.length() - 1);
                String arreglo[] = this.ingr.split(";");

                int x = 0;
                int y = 0;
                int num;  //el numero que tendrá el plato
                //buscando el numero a brindarle al nuevo plato
                for (int i = 0; i < plato.size(); i++) {
                        x = this.plato.get(i).getNumero();  //obtiene numero del objeto
                }
                
                num=x+1;
                x++;
                for (int i = 0; i < bebida.size(); i++) {
                     this.bebida.get(i).setNumero(x);
                     x++;
                }

                this.nuevoPlato = new Plato(this.nuevoNom.getText(), num);
                this.nuevoPlato.setCalorias(cc);
                this.nuevoPlato.setIngredientes(arreglo);
                this.nuevoPlato.setPrecio(p);
                this.nuevoPlato.setVecesConsumido(this.nuevoPlato.getVecesConsumido() + 1);
                iiproyecto.main.restaurante.getMenu().agregarPlatillo(this.nuevoPlato); //agrega plato a menu
                Plato pl = this.nuevoPlato.clone();
                System.out.println(pl.getPrecio());
                orden.agregarPlato(pl, can); //un cllon del plato se va a la orden
                for (int i = 0; i < can; i++) {
                    pl = this.nuevoPlato.clone();
                    Pedido pedido = new Pedido(false); //espera a ser preparado
                    pedido.setPlato(pl); //se añaded el clon
                    enlace.añadirCola(pedido); //se agrega a la lista global de los pediods del restaurante
                }
                JOptionPane.showMessageDialog(this, " Se ha agregado el plato a la orden y al menu", " Notificación de sistema ", 1);
                //poner en no visibles los botones y labels otra vez
                this.n.setVisible(false);
                this.n2.setVisible(false);
                this.nuevoC.setVisible(false);
                this.nuevoC.setText("");
                this.c.setVisible(false);
                this.c.setText("");
                this.nuevoI.setVisible(false);
                this.nuevoI.setText("");
                this.nuevoNom.setVisible(false);
                this.nuevoNom.setText("");
                this.nuevoPrecio.setVisible(false);
                this.nuevoPrecio.setText("");
                this.n3.setVisible(false);
                this.n4.setVisible(false);
                this.n5.setVisible(false);  //acceso a botones y labels en falso
                this.n6.setVisible(false);
                this.fuera.setVisible(true);
                this.addIngredient.setVisible(false);
                this.addToMenu.setVisible(false);
            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(this, " Los datos ingresados son incorrectos  ", " Alerta de sistema ", 0);

            }
        } else {
            JOptionPane.showMessageDialog(this, " Los datos ingresados son incorrectos  ", " Alerta de sistema ", 0);
        }

    }//GEN-LAST:event_addToMenuActionPerformed

    private void fueraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fueraActionPerformed
        // TODO add your handling code here:
        this.n.setVisible(true);
        this.n2.setVisible(true);
        this.n3.setVisible(true);
        this.n4.setVisible(true);
        this.n5.setVisible(true);  //acceso a botones y labels en falso
        this.n6.setVisible(true);
        this.nuevoC.setVisible(true);
        this.c.setVisible(true);
        this.nuevoI.setVisible(true);
        this.nuevoNom.setVisible(true);
        this.nuevoPrecio.setVisible(true);
        this.fuera.setVisible(false);
        this.addIngredient.setVisible(true);
        this.addToMenu.setVisible(true);
    }//GEN-LAST:event_fueraActionPerformed

    private void addIngredientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIngredientActionPerformed
        // TODO add your handling code here:
        if (!this.nuevoI.getText().equals("")) {
            this.ingr += this.nuevoI.getText();
            this.ingr += ";";

        } else {
            JOptionPane.showMessageDialog(this, " No especifico un ingrediente", "Alerta de Sistema", 0);
        }

    }//GEN-LAST:event_addIngredientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton addIngredient;
    private javax.swing.JButton addToMenu;
    private javax.swing.JTextField c;
    private javax.swing.JLabel cant;
    private javax.swing.JTextField cantid;
    private javax.swing.JComboBox<String> eleccion;
    private javax.swing.JButton fuera;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mensaje;
    private javax.swing.JLabel n;
    private javax.swing.JLabel n2;
    private javax.swing.JLabel n3;
    private javax.swing.JLabel n4;
    private javax.swing.JLabel n5;
    private javax.swing.JLabel n6;
    private javax.swing.JTextField nuevoC;
    private javax.swing.JTextField nuevoI;
    private javax.swing.JTextField nuevoNom;
    private javax.swing.JTextField nuevoPrecio;
    private javax.swing.JTextField numeroPlato;
    private javax.swing.JTextArea texto;
    // End of variables declaration//GEN-END:variables
}
